import { expect, test } from "@playwright/test";

/**
 * SEO contract — metadata, Open Graph / Twitter cards, and the AutoWash
 * JSON-LD block emitted from src/app/layout.tsx.
 */
test.describe("seo", () => {
  test("title and meta description", async ({ page }) => {
    await page.goto("/");
    await expect(page).toHaveTitle(
      "Auto Detailing & Ceramic Coating | Framingham MA — We Care Car Care",
    );
    const description = page.locator('meta[name="description"]');
    await expect(description).toHaveAttribute(
      "content",
      /Top-rated auto detailing, ceramic coating & paint protection in Framingham/,
    );
  });

  test("Open Graph and Twitter card tags", async ({ page }) => {
    await page.goto("/");
    await expect(page.locator('meta[property="og:title"]')).toHaveAttribute(
      "content",
      "Auto Detailing & Ceramic Coating | Framingham MA",
    );
    await expect(page.locator('meta[property="og:type"]')).toHaveAttribute("content", "website");
    await expect(page.locator('meta[property="og:image"]')).toHaveAttribute(
      "content",
      /\/images\/hero-car\.webp$/,
    );
    await expect(page.locator('meta[name="twitter:card"]')).toHaveAttribute(
      "content",
      "summary_large_image",
    );
  });

  test("html lang attribute set", async ({ page }) => {
    await page.goto("/");
    await expect(page.locator("html")).toHaveAttribute("lang", "en");
  });

  test("AutoWash JSON-LD carries business facts", async ({ page }) => {
    await page.goto("/");
    const raw = await page
      .locator('script[type="application/ld+json"]')
      .first()
      .textContent();
    expect(raw).toBeTruthy();
    const json = JSON.parse(raw as string) as Record<string, unknown>;
    expect(json["@type"]).toBe("AutoWash");
    expect(json["telephone"]).toBe("+1-508-290-7476");
    const address = json["address"] as Record<string, string>;
    expect(address.addressLocality).toBe("Framingham");
    expect(address.addressRegion).toBe("MA");
    const rating = json["aggregateRating"] as Record<string, string>;
    expect(rating.ratingValue).toBe("5.0");
    // areaServed enumerates the service-area cities
    const areas = json["areaServed"] as Array<Record<string, string>>;
    expect(areas.length).toBeGreaterThan(3);
  });

  test("AutoWash JSON-LD declares its own URL (SEO parity G3)", async ({ page }) => {
    await page.goto("/");
    const raw = await page
      .locator('script[type="application/ld+json"]')
      .first()
      .textContent();
    const json = JSON.parse(raw as string) as Record<string, unknown>;
    // Must be the canonical site URL (env-driven via metadataBase's siteUrl),
    // not localhost and not the original source site.
    expect(String(json["url"])).toMatch(/^https:\/\/car-care\.jesspete\.shop\/?$/);
  });

  test("FAQPage JSON-LD mirrors the rendered FAQs (SEO parity G1)", async ({ page }) => {
    await page.goto("/");
    // The FAQPage block is the second JSON-LD script (AutoWash is first).
    const blocks = await page.locator('script[type="application/ld+json"]').allTextContents();
    const parsed = blocks.map((raw) => JSON.parse(raw) as Record<string, unknown>);
    const faqPage = parsed.find((b) => b["@type"] === "FAQPage");
    expect(faqPage, "FAQPage JSON-LD block is missing").toBeTruthy();
    const mainEntity = faqPage?.["mainEntity"] as Array<
      Record<string, unknown> & { name: string; acceptedAnswer: { answerText: string } }
    >;
    // Same count as the FAQS array in content.ts (single source of truth).
    expect(mainEntity.length).toBe(9);
    expect(mainEntity[0].name).toContain("difference between the Essential and Premium");
    expect(mainEntity[0].acceptedAnswer.answerText.length).toBeGreaterThan(80);
    for (const item of mainEntity) {
      expect(item["@type"]).toBe("Question");
      expect((item.acceptedAnswer as Record<string, unknown>)["@type"]).toBe("Answer");
    }
  });

  test("canonical link points at the live site URL (SEO parity G2)", async ({ page }) => {
    await page.goto("/");
    const canonical = page.locator('link[rel="canonical"]');
    await expect(canonical).toHaveCount(1);
    await expect(canonical).toHaveAttribute(
      "href",
      /^https:\/\/car-care\.jesspete\.shop\/?$/,
    );
  });

  test("theme-color meta matches the dark canvas (SEO parity G4)", async ({ page }) => {
    await page.goto("/");
    const themeColor = page.locator('meta[name="theme-color"]');
    await expect(themeColor).toHaveAttribute("content", "#0a0b0d");
  });

  test("legacy favicon.ico and apple-touch-icon resolve (SEO parity G5)", async ({ page }) => {
    await page.goto("/");
    // Legacy crawlers and browser tabs request /favicon.ico by convention.
    const ico = await page.request.get("/favicon.ico");
    expect(ico.status()).toBe(200);
    expect(ico.headers()["content-type"]).toContain("image/");
    // iOS bookmarks follow the apple-touch-icon link tag (auto-generated by
    // the src/app/apple-icon.png file convention).
    const appleLink = page.locator('link[rel="apple-touch-icon"]');
    await expect(appleLink).toHaveCount(1);
    const href = await appleLink.first().getAttribute("href");
    expect(href).toBeTruthy();
    const apple = await page.request.get(href as string);
    expect(apple.status()).toBe(200);
  });
});
